name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: obsidian-mynb # Change this to the name of your plugin-id folder
  TAG: ${{ github.ref_name }}


jobs:
  release-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'pnpm'

      - name: Install dependencies and BuildPackage
        run: |
          pnpm install
          pnpm run build
          zip -r output/${{ env.PLUGIN_NAME }}-${{ env.TAG }}.zip output/${{ env.PLUGIN_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
          files: |
            output/${{ env.PLUGIN_NAME }}/*
