name: CD

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: obsidian-mynb # Change this to the name of your plugin-id folder


jobs:
  release-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'pnpm'

      - name: Install dependencies and BuildPackage
        run: |
          pnpm install
          pnpm run build
          zip -r ${{ env.PLUGIN_NAME }}-${{ env.tag }}.zip output/${{ env.PLUGIN_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # main.css
          generate_release_notes: true
          draft: true
          files: |
            output/${{ env.PLUGIN_NAME }}/main.js
            output/${{ env.PLUGIN_NAME }}/manifest.json
            output/${{ env.PLUGIN_NAME }}/styles.css
            ${{ env.PLUGIN_NAME }}-${{ env.tag }}.zip